on: 
  push:
    branches: 
      - master

jobs:
  visualize:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@V4
      - name: Update diagram
        id: make_diagram
        uses: githubocto/repo-visualizer@0.7.1
        with:
          output_file: "diagram.svg"
          artifact_name: "diagram"
